### ISSUE TITLE
Only renders emojis on first page of the atlas

### ISSUE THREAD

**Issue by alexdriedger** [DavidPDev/gdx-EmojiSupport#2]
Everything worked great when I used the emoji set you provided.

When I wanted to use more emojis (I packed about 1300 from noto-color), it generated more than one texture page for the atlas (in this case 5 png files for the atlas). Any emojis from pages that were not the first page were rendered as the emoji in the same location in the texture on the first page.

Ex: The sword emoji was on the 4th page, 2nd column, 8th row. It got rendered as the soap emoji, which was on the 1st page, 2nd column, 8th row. This happened with all emojis not on the first page.

I think it has to do with

https://github.com/DavidPDev/gdx-EmojiSupport/blob/83963e3a5910563502d3958c06dc91759cc2a3a2/core/src/com/badlogic/gdx/graphics/g2d/EmojiSupport.java#L116

Because page is always set to 1

**Comment by DavidPDev** [comment]
Thank you very much for catching this "bug". Yes, I'm sure it has to be with the line you stated. I will check it today.

**Comment by DavidPDev** [comment]
Should be fixed now.
Just get the new version of the file "EmojiSupport.java".
Let me know if it works! Thank you.

**Comment by alexdriedger** [comment]
It works for me! Thanks!
